### ISSUE TITLE
How to work with multiple  queries

### ISSUE THREAD

**Issue by Nader2004** [vedartm/paginate_firestore#90] opened 2021-07-29 09:14 UTC
Hello,

Let's say I have two queries in the app : 

```
Query query1;
Query query2;

PaginateFirestore(
 query: query1 && query2,
)

```

I am searching for a way to combine them together but i couldn't find a  way. Is there any suggestion.
It could be even more helpful if you added a pramater like `documentSnapshots` : 

```
PaginateFirestore(
 documentSnapshots:  ,
)

```

Because this could make it easier in terms of the problem context to combine now multiple documentSnapshots.

Thanks!

**Comment by vedartm** [comment] 2021-08-07 13:49
Hi @Nader2004. If you are comfortable with using `documentSnapshots`, you can go with the package [`pagination_view`](https://pub.dev/packages/pagination_view). I made it for a general use case.

**Comment by vedartm** [comment] 2021-08-07 13:52
Closing this as it is a duplicate of #58

**Closed by vedartm** 2021-08-07 13:52 UTC
